### ISSUE TITLE
GUI Überlagerung

### ISSUE THREAD

**Issue by Niko8487** [ThEmKay/hello-rabenau#5]
Im Bereich der Places kann es vorkommen, dass Teile der Namen von Datensätzen in der Listenansicht von den Icons der Kosteneinschätzung überblendet werden. Hier wäre es hübscher, wenn diese Icons etwas nach unten versetzt werden.

**Comment by ThEmKay** [comment]
Wie bei den Ärzten befindet sich das Icon nun unten rechts.
